name: Pilot

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request: {}

defaults:
  run:
    shell: pwsh

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.select.outputs.environment }}
    steps:
      - name: Select environment
        id: select
        run: 'Write-Host ("::set-output name=environment::" + ("${{ github.ref_type }}" -eq "tag" ? "PowerShell Gallery" : "MyGet"))'

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: prepare
    environment: ${{ needs.prepare.outputs.environment }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Publish
        run: |
          . ./Publish-PowerShellModule.ps1
          Publish-PowerShellModule `
              -Ref ("${{ github.event_name }}" -eq "pull_request" ? "${{ github.head_ref }}" : "${{ github.ref_name }}") `
              -Build ${{ github.run_number }} `
              -NuGetApiKey "${{ secrets.NUGET_API_KEY }}" `
              -NuGetUrl "${{ vars.NUGET_URL }}" `
              -InformationAction Continue