name: Pilot

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request: {}

defaults:
  run:
    shell: pwsh

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.select.outputs.environment }}
    steps:
      - name: Select environment
        id: select
        run: |
          $InformationPreference = "Continue"
          $environment = "${{ github.ref_type }}" -eq "tag" ? "PowerShell Gallery" : "MyGet"
          Write-Output "environment=$environment" >> "$Env:GITHUB_OUTPUT"

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: prepare
    environment: ${{ needs.prepare.outputs.environment }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Publish
        id: publish
        run: |
          $InformationPreference = "Continue"

          $manifest = Import-PowerShellDataFile ./Pilot.psd1
          foreach ($module in $manifest.RequiredModules) {
              Install-Module $module.ModuleName -Force -RequiredVersion $module.RequiredVersion
          }

          Import-Module ./Pilot.psd1

          $packageFileName = Publish-PowerShellModule `
              -Ref ("${{ github.event_name }}" -eq "pull_request" ? "${{ github.head_ref }}" : "${{ github.ref_name }}") `
              -Build ${{ github.run_number }} `
              -NuGetApiKey "${{ secrets.NUGET_API_KEY }}" `
              -NuGetUrl "${{ vars.NUGET_URL }}"

          Write-Output "package=$packageFileName" >> "$Env:GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.publish.outputs.package }}
          path: artifacts/${{ steps.publish.outputs.package }}
